name: docker-push

on:
  push:
    tags:
    - 'v*'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - id: get_version
      uses: battila7/get-version-action@v2

    - name: Build and Push
      env:
        REPOSITORY: dohq/dockerhub_ratelimit_exporter
        VERSION: ${{ steps.get_version.outputs.version-without-v }}
        DOCKER_BUILDKIT: 1
      run: |
        make container_build
        make container_cache
        make container_push
